import './globals.css'
import './components/navbar'
import Navbar from './components/navbar'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCheckSquare, faCoffee } from '@fortawesome/free-solid-svg-icons'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex justify-center bg-gray-background overflow-hidden font-pfd font-normal'>
        <div className='w-11/12 h-screen bg-red '>

          <div className=' sticky mb-4'><Navbar></Navbar></div>
          <div className='w-full h-5/6 bg-white'>
            {children}
          </div>
          <div>
            <footer className=' text-center mt-5 mb-3 pb-3 text-gray-light'>Copyright &copy; 2023 Akaiko</footer>
          </div>

        </div>
      </body>
    </html>
  )
}
