import './globals.css'
import './components/navbar'
import Navbar from './components/navbar'
import Footer from './components/footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex justify-center bg-gray-background overflow-hidden font-pfd font-normal'>
        <div className='w-5/6 md:w-11/12 h-screen z-0 '>

          <div className='sticky mb-4 h-fit '><Navbar></Navbar></div>

          <div className='w-full h-5/6 bg-white'>
            {children}
          </div>
        </div>
        <div className='fixed bottom-0 w-full bg-gray-background'><Footer></Footer></div>



        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js" async />
        <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" async />
      </body>
    </html>
  )
}
